services:
  competition:
    build:
      context: .
      dockerfile: ./cmd/competition/Dockerfile
    command:
      - "--address"
      - "0.0.0.0:11234"
    expose:
      - "11234"
    environment:
      - "ENV=dev-compose"
  simple:
    build:
      context: .
      dockerfile: ./cmd/simpled/Dockerfile
    command:
      - "game-instance"
      - "--competition-service"
      - "competition:11234"
      - "--service-address"
      - "0.0.0.0:11235"
      - "--advertise-address"
      - "simple:11235"
    expose:
      - "11235"
    environment:
      - "ENV=dev-compose"
    depends_on:
      - competition
  player_1:
    build:
      context: .
      dockerfile: ./cmd/simple/Dockerfile
    command:
      - "--competition-address"
      - "competition:11234"
      - "--startup-delay=1s"
    environment:
      - "ENV=dev-compose"
    depends_on:
      - simple
  player_2:
    build:
      context: .
      dockerfile: ./cmd/simple/Dockerfile
    command:
      - "--competition-address"
      - "competition:11234"
      - "--startup-delay=1s"
    environment:
      - "ENV=dev-compose"
    depends_on:
      - competition
      - simple
