// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.17.3
// source: t3/network/game.proto

package network

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartGameIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YourPlayer int64 `protobuf:"varint,1,opt,name=yourPlayer,proto3" json:"yourPlayer,omitempty"`
}

func (x *StartGameIn) Reset() {
	*x = StartGameIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameIn) ProtoMessage() {}

func (x *StartGameIn) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameIn.ProtoReflect.Descriptor instead.
func (*StartGameIn) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{0}
}

func (x *StartGameIn) GetYourPlayer() int64 {
	if x != nil {
		return x.YourPlayer
	}
	return 0
}

type StartGameOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID int64 `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
}

func (x *StartGameOut) Reset() {
	*x = StartGameOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameOut) ProtoMessage() {}

func (x *StartGameOut) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameOut.ProtoReflect.Descriptor instead.
func (*StartGameOut) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{1}
}

func (x *StartGameOut) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

type JoinGameIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// gameID is the game to connect to for playing.
	GameID string `protobuf:"bytes,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
}

func (x *JoinGameIn) Reset() {
	*x = JoinGameIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameIn) ProtoMessage() {}

func (x *JoinGameIn) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameIn.ProtoReflect.Descriptor instead.
func (*JoinGameIn) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{2}
}

func (x *JoinGameIn) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

type T3PushEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Initial    *JoinGameOut  `protobuf:"bytes,1,opt,name=initial,proto3,oneof" json:"initial,omitempty"`
	Move       *MoveMadeIn   `protobuf:"bytes,2,opt,name=move,proto3,oneof" json:"move,omitempty"`
	Conclusion *ConclusionIn `protobuf:"bytes,3,opt,name=conclusion,proto3,oneof" json:"conclusion,omitempty"`
	DoTurn     *PlayerTurn   `protobuf:"bytes,4,opt,name=doTurn,proto3,oneof" json:"doTurn,omitempty"`
}

func (x *T3PushEvent) Reset() {
	*x = T3PushEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *T3PushEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*T3PushEvent) ProtoMessage() {}

func (x *T3PushEvent) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use T3PushEvent.ProtoReflect.Descriptor instead.
func (*T3PushEvent) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{3}
}

func (x *T3PushEvent) GetInitial() *JoinGameOut {
	if x != nil {
		return x.Initial
	}
	return nil
}

func (x *T3PushEvent) GetMove() *MoveMadeIn {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *T3PushEvent) GetConclusion() *ConclusionIn {
	if x != nil {
		return x.Conclusion
	}
	return nil
}

func (x *T3PushEvent) GetDoTurn() *PlayerTurn {
	if x != nil {
		return x.DoTurn
	}
	return nil
}

type JoinGameOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// yourPlayer indicates the player ID the client is connected to.
	YourPlayer int64 `protobuf:"varint,1,opt,name=yourPlayer,proto3" json:"yourPlayer,omitempty"`
}

func (x *JoinGameOut) Reset() {
	*x = JoinGameOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameOut) ProtoMessage() {}

func (x *JoinGameOut) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameOut.ProtoReflect.Descriptor instead.
func (*JoinGameOut) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{4}
}

func (x *JoinGameOut) GetYourPlayer() int64 {
	if x != nil {
		return x.YourPlayer
	}
	return 0
}

type PushMoveIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID string       `protobuf:"bytes,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	Move   *NextMoveOut `protobuf:"bytes,2,opt,name=move,proto3" json:"move,omitempty"`
}

func (x *PushMoveIn) Reset() {
	*x = PushMoveIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMoveIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMoveIn) ProtoMessage() {}

func (x *PushMoveIn) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMoveIn.ProtoReflect.Descriptor instead.
func (*PushMoveIn) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{5}
}

func (x *PushMoveIn) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

func (x *PushMoveIn) GetMove() *NextMoveOut {
	if x != nil {
		return x.Move
	}
	return nil
}

type PushMoveOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushMoveOut) Reset() {
	*x = PushMoveOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMoveOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMoveOut) ProtoMessage() {}

func (x *PushMoveOut) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMoveOut.ProtoReflect.Descriptor instead.
func (*PushMoveOut) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{6}
}

type MoveMadeIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player int64 `protobuf:"varint,1,opt,name=player,proto3" json:"player,omitempty"`
	Row    int64 `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Column int64 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	GameID int64 `protobuf:"varint,4,opt,name=gameID,proto3" json:"gameID,omitempty"`
}

func (x *MoveMadeIn) Reset() {
	*x = MoveMadeIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveMadeIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMadeIn) ProtoMessage() {}

func (x *MoveMadeIn) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMadeIn.ProtoReflect.Descriptor instead.
func (*MoveMadeIn) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{7}
}

func (x *MoveMadeIn) GetPlayer() int64 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *MoveMadeIn) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *MoveMadeIn) GetColumn() int64 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *MoveMadeIn) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

type MoveMadeOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveMadeOut) Reset() {
	*x = MoveMadeOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveMadeOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMadeOut) ProtoMessage() {}

func (x *MoveMadeOut) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMadeOut.ProtoReflect.Descriptor instead.
func (*MoveMadeOut) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{8}
}

type NextMoveIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID int64 `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
}

func (x *NextMoveIn) Reset() {
	*x = NextMoveIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextMoveIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextMoveIn) ProtoMessage() {}

func (x *NextMoveIn) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextMoveIn.ProtoReflect.Descriptor instead.
func (*NextMoveIn) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{9}
}

func (x *NextMoveIn) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

type NextMoveOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row    int64 `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Column int64 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *NextMoveOut) Reset() {
	*x = NextMoveOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextMoveOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextMoveOut) ProtoMessage() {}

func (x *NextMoveOut) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextMoveOut.ProtoReflect.Descriptor instead.
func (*NextMoveOut) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{10}
}

func (x *NextMoveOut) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *NextMoveOut) GetColumn() int64 {
	if x != nil {
		return x.Column
	}
	return 0
}

type ConclusionIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID    int64 `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	Stalemate bool  `protobuf:"varint,2,opt,name=stalemate,proto3" json:"stalemate,omitempty"`
	Winner    int64 `protobuf:"varint,3,opt,name=winner,proto3" json:"winner,omitempty"`
	Withdraw  bool  `protobuf:"varint,4,opt,name=withdraw,proto3" json:"withdraw,omitempty"`
}

func (x *ConclusionIn) Reset() {
	*x = ConclusionIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConclusionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConclusionIn) ProtoMessage() {}

func (x *ConclusionIn) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConclusionIn.ProtoReflect.Descriptor instead.
func (*ConclusionIn) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{11}
}

func (x *ConclusionIn) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *ConclusionIn) GetStalemate() bool {
	if x != nil {
		return x.Stalemate
	}
	return false
}

func (x *ConclusionIn) GetWinner() int64 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *ConclusionIn) GetWithdraw() bool {
	if x != nil {
		return x.Withdraw
	}
	return false
}

type ConclusionOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConclusionOut) Reset() {
	*x = ConclusionOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConclusionOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConclusionOut) ProtoMessage() {}

func (x *ConclusionOut) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConclusionOut.ProtoReflect.Descriptor instead.
func (*ConclusionOut) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{12}
}

type PlayerTurn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayerTurn) Reset() {
	*x = PlayerTurn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t3_network_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTurn) ProtoMessage() {}

func (x *PlayerTurn) ProtoReflect() protoreflect.Message {
	mi := &file_t3_network_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTurn.ProtoReflect.Descriptor instead.
func (*PlayerTurn) Descriptor() ([]byte, []int) {
	return file_t3_network_game_proto_rawDescGZIP(), []int{13}
}

var File_t3_network_game_proto protoreflect.FileDescriptor

var file_t3_network_game_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x33, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x79, 0x6f, 0x75, 0x72, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x79, 0x6f, 0x75, 0x72,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x24,
	0x0a, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x44, 0x22, 0xed, 0x01, 0x0a, 0x0b, 0x54, 0x33, 0x50, 0x75, 0x73, 0x68, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65,
	0x4f, 0x75, 0x74, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x88, 0x01,
	0x01, 0x12, 0x24, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x48, 0x01, 0x52, 0x04,
	0x6d, 0x6f, 0x76, 0x65, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x63, 0x6c,
	0x75, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f,
	0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x48, 0x02, 0x52, 0x0a, 0x63, 0x6f,
	0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x06, 0x64,
	0x6f, 0x54, 0x75, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x54, 0x75, 0x72, 0x6e, 0x48, 0x03, 0x52, 0x06, 0x64, 0x6f, 0x54, 0x75,
	0x72, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63,
	0x6f, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x64, 0x6f,
	0x54, 0x75, 0x72, 0x6e, 0x22, 0x2d, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65,
	0x4f, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x79, 0x6f, 0x75, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x79, 0x6f, 0x75, 0x72, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0x46, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x49,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x6f, 0x76,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x6f,
	0x76, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50,
	0x75, 0x73, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x75, 0x74, 0x22, 0x66, 0x0a, 0x0a, 0x4d, 0x6f,
	0x76, 0x65, 0x4d, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72,
	0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x44, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x64, 0x65, 0x4f, 0x75,
	0x74, 0x22, 0x24, 0x0a, 0x0a, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x37, 0x0a, 0x0b, 0x4e, 0x65, 0x78, 0x74, 0x4d,
	0x6f, 0x76, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x22, 0x78, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x6c,
	0x65, 0x6d, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x6c, 0x65, 0x6d, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6f,
	0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x75, 0x72, 0x6e, 0x32, 0xa8, 0x01, 0x0a, 0x02, 0x54, 0x33,
	0x12, 0x28, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x0c, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x1a, 0x0d, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x6d, 0x6f,
	0x76, 0x65, 0x4d, 0x61, 0x64, 0x65, 0x12, 0x0b, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x64,
	0x65, 0x49, 0x6e, 0x1a, 0x0c, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x64, 0x65, 0x4f, 0x75,
	0x74, 0x12, 0x25, 0x0a, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0b, 0x2e,
	0x4e, 0x65, 0x78, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x1a, 0x0c, 0x2e, 0x4e, 0x65, 0x78,
	0x74, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x64, 0x12, 0x0d, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x1a, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f,
	0x6e, 0x4f, 0x75, 0x74, 0x32, 0x59, 0x0a, 0x06, 0x54, 0x33, 0x50, 0x75, 0x73, 0x68, 0x12, 0x2c,
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x12,
	0x0b, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x1a, 0x0c, 0x2e, 0x54,
	0x33, 0x50, 0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x12, 0x21, 0x0a, 0x04,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x0b, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x49,
	0x6e, 0x1a, 0x0c, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x75, 0x74, 0x42,
	0x0c, 0x5a, 0x0a, 0x74, 0x33, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_t3_network_game_proto_rawDescOnce sync.Once
	file_t3_network_game_proto_rawDescData = file_t3_network_game_proto_rawDesc
)

func file_t3_network_game_proto_rawDescGZIP() []byte {
	file_t3_network_game_proto_rawDescOnce.Do(func() {
		file_t3_network_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_t3_network_game_proto_rawDescData)
	})
	return file_t3_network_game_proto_rawDescData
}

var file_t3_network_game_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_t3_network_game_proto_goTypes = []any{
	(*StartGameIn)(nil),   // 0: StartGameIn
	(*StartGameOut)(nil),  // 1: StartGameOut
	(*JoinGameIn)(nil),    // 2: JoinGameIn
	(*T3PushEvent)(nil),   // 3: T3PushEvent
	(*JoinGameOut)(nil),   // 4: JoinGameOut
	(*PushMoveIn)(nil),    // 5: PushMoveIn
	(*PushMoveOut)(nil),   // 6: PushMoveOut
	(*MoveMadeIn)(nil),    // 7: MoveMadeIn
	(*MoveMadeOut)(nil),   // 8: MoveMadeOut
	(*NextMoveIn)(nil),    // 9: NextMoveIn
	(*NextMoveOut)(nil),   // 10: NextMoveOut
	(*ConclusionIn)(nil),  // 11: ConclusionIn
	(*ConclusionOut)(nil), // 12: ConclusionOut
	(*PlayerTurn)(nil),    // 13: PlayerTurn
}
var file_t3_network_game_proto_depIdxs = []int32{
	4,  // 0: T3PushEvent.initial:type_name -> JoinGameOut
	7,  // 1: T3PushEvent.move:type_name -> MoveMadeIn
	11, // 2: T3PushEvent.conclusion:type_name -> ConclusionIn
	13, // 3: T3PushEvent.doTurn:type_name -> PlayerTurn
	10, // 4: PushMoveIn.move:type_name -> NextMoveOut
	0,  // 5: T3.startGame:input_type -> StartGameIn
	7,  // 6: T3.moveMade:input_type -> MoveMadeIn
	9,  // 7: T3.nextMove:input_type -> NextMoveIn
	11, // 8: T3.concluded:input_type -> ConclusionIn
	2,  // 9: T3Push.connectToGame:input_type -> JoinGameIn
	5,  // 10: T3Push.move:input_type -> PushMoveIn
	1,  // 11: T3.startGame:output_type -> StartGameOut
	8,  // 12: T3.moveMade:output_type -> MoveMadeOut
	10, // 13: T3.nextMove:output_type -> NextMoveOut
	12, // 14: T3.concluded:output_type -> ConclusionOut
	3,  // 15: T3Push.connectToGame:output_type -> T3PushEvent
	6,  // 16: T3Push.move:output_type -> PushMoveOut
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_t3_network_game_proto_init() }
func file_t3_network_game_proto_init() {
	if File_t3_network_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_t3_network_game_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StartGameIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StartGameOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*JoinGameIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*T3PushEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*JoinGameOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PushMoveIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PushMoveOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*MoveMadeIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*MoveMadeOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*NextMoveIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*NextMoveOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ConclusionIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ConclusionOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t3_network_game_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerTurn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_t3_network_game_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_t3_network_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_t3_network_game_proto_goTypes,
		DependencyIndexes: file_t3_network_game_proto_depIdxs,
		MessageInfos:      file_t3_network_game_proto_msgTypes,
	}.Build()
	File_t3_network_game_proto = out.File
	file_t3_network_game_proto_rawDesc = nil
	file_t3_network_game_proto_goTypes = nil
	file_t3_network_game_proto_depIdxs = nil
}
