// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.17.3
// source: junk/inProc/example/simple.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloIn) Reset() {
	*x = HelloIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_junk_inProc_example_simple_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloIn) ProtoMessage() {}

func (x *HelloIn) ProtoReflect() protoreflect.Message {
	mi := &file_junk_inProc_example_simple_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloIn.ProtoReflect.Descriptor instead.
func (*HelloIn) Descriptor() ([]byte, []int) {
	return file_junk_inProc_example_simple_proto_rawDescGZIP(), []int{0}
}

func (x *HelloIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *HelloOut) Reset() {
	*x = HelloOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_junk_inProc_example_simple_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloOut) ProtoMessage() {}

func (x *HelloOut) ProtoReflect() protoreflect.Message {
	mi := &file_junk_inProc_example_simple_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloOut.ProtoReflect.Descriptor instead.
func (*HelloOut) Descriptor() ([]byte, []int) {
	return file_junk_inProc_example_simple_proto_rawDescGZIP(), []int{1}
}

func (x *HelloOut) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_junk_inProc_example_simple_proto protoreflect.FileDescriptor

var file_junk_inProc_example_simple_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6a, 0x75, 0x6e, 0x6b, 0x2f, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x49, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x26, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x4f, 0x75, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x32, 0x2b, 0x0a, 0x06, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x08, 0x73, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x08, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x49, 0x6e, 0x1a, 0x09, 0x2e, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x6a, 0x75, 0x6e, 0x6b, 0x2f, 0x69,
	0x6e, 0x50, 0x72, 0x6f, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_junk_inProc_example_simple_proto_rawDescOnce sync.Once
	file_junk_inProc_example_simple_proto_rawDescData = file_junk_inProc_example_simple_proto_rawDesc
)

func file_junk_inProc_example_simple_proto_rawDescGZIP() []byte {
	file_junk_inProc_example_simple_proto_rawDescOnce.Do(func() {
		file_junk_inProc_example_simple_proto_rawDescData = protoimpl.X.CompressGZIP(file_junk_inProc_example_simple_proto_rawDescData)
	})
	return file_junk_inProc_example_simple_proto_rawDescData
}

var file_junk_inProc_example_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_junk_inProc_example_simple_proto_goTypes = []any{
	(*HelloIn)(nil),  // 0: HelloIn
	(*HelloOut)(nil), // 1: HelloOut
}
var file_junk_inProc_example_simple_proto_depIdxs = []int32{
	0, // 0: Simple.sayHello:input_type -> HelloIn
	1, // 1: Simple.sayHello:output_type -> HelloOut
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_junk_inProc_example_simple_proto_init() }
func file_junk_inProc_example_simple_proto_init() {
	if File_junk_inProc_example_simple_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_junk_inProc_example_simple_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HelloIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_junk_inProc_example_simple_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HelloOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_junk_inProc_example_simple_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_junk_inProc_example_simple_proto_goTypes,
		DependencyIndexes: file_junk_inProc_example_simple_proto_depIdxs,
		MessageInfos:      file_junk_inProc_example_simple_proto_msgTypes,
	}.Build()
	File_junk_inProc_example_simple_proto = out.File
	file_junk_inProc_example_simple_proto_rawDesc = nil
	file_junk_inProc_example_simple_proto_goTypes = nil
	file_junk_inProc_example_simple_proto_depIdxs = nil
}
