name: Trigger release on main push

on:
  push:
    branches:
      - main

jobs:
  release_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.version.outputs.new_tag }}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-tag
      cancel-in-progress: true

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

  artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-artifacts
      cancel-in-progress: true

    permissions:
      contents: write
      packages: write
    needs:
      - release_tag
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release_tag.outputs.tag_version }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Build Go Artifacts
        run: |
          ./dev.sh release
          ./release-package.sh

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            linux-amd64.tar.gz
            linux-arm64.tar.gz
            darwin-arm64.tar.gz

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push competition image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cmd/competition/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/npcs/competition:latest
            ghcr.io/${{ github.repository_owner }}/npcs/competition:${{ needs.release_tag.outputs.tag_version }}

      - name: Build and push simple image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cmd/simple/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/npcs/simple:latest
            ghcr.io/${{ github.repository_owner }}/npcs/simple:${{ needs.release_tag.outputs.tag_version }}
